#!/usr/bin/env python3
"""Setup Supabase table and verify connection."""

import os
import sys
from supabase import create_client, Client

def setup_supabase():
    """Initialize Supabase and create irenginiai table."""
    supabase_url = os.getenv("SUPABASE_URL")
    supabase_key = os.getenv("SUPABASE_KEY")
    
    if not supabase_url or not supabase_key:
        print("Error: SUPABASE_URL and SUPABASE_KEY environment variables not set")
        return False
    
    try:
        # Create Supabase client
        supabase: Client = create_client(supabase_url, supabase_key)
        print(f"✓ Connected to Supabase: {supabase_url}")
        
        # Test connection by querying the table
        response = supabase.table("irenginiai").select("*").limit(1).execute()
        print("✓ Table 'irenginiai' exists and is accessible")
        print(f"  Current records: {len(response.data)}")
        
        return True
    except Exception as e:
        print(f"✗ Error: {e}")
        print("\nTo create the 'irenginiai' table, run this SQL in Supabase SQL Editor:")
        print("""
CREATE TABLE irenginiai (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ip_adresas TEXT UNIQUE NOT NULL,
    mac_adresas TEXT,
    host_name TEXT,
    duomenu_perdavimo_greitis TEXT,
    scan_time TIMESTAMP DEFAULT NOW()
);

-- Enable Row Level Security (optional but recommended)
ALTER TABLE irenginiai ENABLE ROW LEVEL SECURITY;

-- Create policy to allow public access (for development only)
CREATE POLICY "Allow public access" ON irenginiai
  FOR ALL USING (true) WITH CHECK (true);
        """)
        return False

if __name__ == "__main__":
    success = setup_supabase()
    sys.exit(0 if success else 1)
