#!/usr/bin/env python3
"""Test network scanner with Supabase."""

import os
import sys

# Set Supabase credentials
os.environ["SUPABASE_URL"] = "https://mxcjlnezxewqxdrjayor.supabase.co"
os.environ["SUPABASE_KEY"] = "sb_publishable_OfQ4HjEEoeIDGtaYMFOXVg_LJG8uxDp"

from network_scanner import NetworkScanner

def test_sqlite():
    """Test SQLite backend."""
    print("=" * 60)
    print("Test 1: SQLite Backend (Local Database)")
    print("=" * 60)
    
    try:
        scanner = NetworkScanner(use_supabase=False)
        print("✓ Created scanner with SQLite")
        
        scanner.scan_network()
        print(f"✓ Network scan completed - found {len(scanner.devices)} devices")
        
        if scanner.devices:
            scanner.save_to_database()
            print("✓ Saved to SQLite database")
            
            devices = scanner.get_all_devices()
            print(f"✓ Retrieved {len(devices)} devices from database")
            scanner.print_results()
        else:
            print("⚠ No devices found (may need admin privileges)")
        
        return True
    except Exception as e:
        print(f"✗ Error: {e}")
        return False

def test_supabase():
    """Test Supabase backend."""
    print("\n" + "=" * 60)
    print("Test 2: Supabase Backend (Cloud Database)")
    print("=" * 60)
    
    try:
        # First test connection
        from supabase import create_client
        url = os.getenv("SUPABASE_URL")
        key = os.getenv("SUPABASE_KEY")
        
        client = create_client(url, key)
        print(f"✓ Connected to Supabase: {url}")
        
        # Test table access
        response = client.table("irenginiai").select("*").limit(1).execute()
        print(f"✓ Table 'irenginiai' is accessible")
        print(f"  Current records in Supabase: {len(response.data) if response.data else 0}")
        
        # Now test scanner with Supabase
        scanner = NetworkScanner(use_supabase=True)
        print("✓ Created scanner with Supabase backend")
        
        scanner.scan_network()
        print(f"✓ Network scan completed - found {len(scanner.devices)} devices")
        
        if scanner.devices:
            scanner.save_to_database()
            print("✓ Saved to Supabase")
            
            devices = scanner.get_all_devices()
            print(f"✓ Retrieved {len(devices)} devices from Supabase")
            
            # Show first few records
            for i, device in enumerate(devices[:3]):
                print(f"  [{i+1}] {device['ip_adresas']} - {device['host_name']}")
        else:
            print("⚠ No devices found (may need admin privileges)")
        
        return True
    except ModuleNotFoundError:
        print("✗ Supabase library not installed")
        print("  Install with: pip install supabase")
        return False
    except Exception as e:
        print(f"✗ Error: {e}")
        return False

def manual_insert_test():
    """Test manual insert to Supabase."""
    print("\n" + "=" * 60)
    print("Test 3: Manual Insert to Supabase (Verify Write Access)")
    print("=" * 60)
    
    try:
        from supabase import create_client
        from datetime import datetime
        
        url = os.getenv("SUPABASE_URL")
        key = os.getenv("SUPABASE_KEY")
        
        client = create_client(url, key)
        
        # Insert test device
        test_data = {
            "ip_adresas": "192.168.1.99",
            "mac_adresas": "00:11:22:33:44:55",
            "host_name": "test-device",
            "duomenu_perdavimo_greitis": "10ms response time",
            "scan_time": datetime.now().isoformat()
        }
        
        response = client.table("irenginiai").upsert(test_data, on_conflict='ip_adresas').execute()
        print(f"✓ Test record inserted/updated successfully")
        print(f"  IP: {test_data['ip_adresas']}")
        print(f"  Hostname: {test_data['host_name']}")
        
        return True
    except Exception as e:
        print(f"✗ Error: {e}")
        if "irenginiai" in str(e):
            print("\n  Note: You need to create the 'irenginiai' table in Supabase:")
            print("""
            Go to: https://mxcjlnezxewqxdrjayor.supabase.co/project/default/sql
            
            Run this SQL:
            
            CREATE TABLE irenginiai (
                id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                ip_adresas TEXT UNIQUE NOT NULL,
                mac_adresas TEXT,
                host_name TEXT,
                duomenu_perdavimo_greitis TEXT,
                scan_time TIMESTAMP DEFAULT NOW()
            );
            """)
        return False

if __name__ == "__main__":
    print("\n" + "=" * 60)
    print("NETWORK SCANNER TESTING")
    print("=" * 60)
    
    # Run tests
    sqlite_ok = test_sqlite()
    supabase_ok = test_supabase()
    manual_ok = manual_insert_test()
    
    # Summary
    print("\n" + "=" * 60)
    print("TEST SUMMARY")
    print("=" * 60)
    print(f"SQLite Backend:    {'✓ PASS' if sqlite_ok else '✗ FAIL'}")
    print(f"Supabase Backend:  {'✓ PASS' if supabase_ok else '✗ FAIL'}")
    print(f"Manual Insert:     {'✓ PASS' if manual_ok else '✗ FAIL'}")
    print("=" * 60)
